version: "3.9"

services:
  client:
    build:
      context: client
      args:
        - ENV=development
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
      - ./client/package.json:/client/package.json
      - ./client/snowpack.config.js:/client/snowpack.config.js
      - ./client/index.html:/client/index.html
    ports:
      - "8080:8080"
    command: ['npm', 'run', 'devserver']

  api:
    build:
      context: api
      args:
        - ENV=development
    volumes:
      - ./api/app:/api/app
      - ./api/run.sh:/api/run.sh
    depends_on:
      - db
    ports:
      - "8246:8000"
    command: ['./run.sh', 'serve_dev']

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: